export interface AddressInfo {
  addressInformationId: number;
  street: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
}

export interface Lead {
  leadId: number;
  source: {
    leadSourceId: number;
    leadSourceName: string;
  };
  industry: string;
  status: string;
  rating: string;
  addressInfor: AddressInfo;
  solution: string;
  firstName: string;
  lastName: string;
  middleName: string | null;
  gender: number;
  title: string;
  email: string;
  phone: string;
  website: string;
  company: string;
  no_employee: number | null;
  createdBy: number;
  createDate: string;
  editDate: string;
  editBy: number;
  isDelete: number;
  children?: Lead[]; // Optional for hierarchical data
}

export const leadsData: Lead[] = [
  {
    leadId: 21,
    source: {
      leadSourceId: 2,
      leadSourceName: "Advertisement",
    },
    industry: "--None--",
    status: "--None--",
    rating: "Warm",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Alice",
    lastName: "Smith",
    middleName: null,
    gender: 0,
    title: "Manager",
    email: "alice.smith@example.com",
    phone: "1234567890",
    website: "www.example.com",
    company: "ABC Company",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 22,
    source: {
      leadSourceId: 2,
      leadSourceName: "Advertisement",
    },
    industry: "Agriculture",
    status: "Unqualified",
    rating: "--None--",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Bob",
    lastName: "Johnson",
    middleName: null,
    gender: 1,
    title: "CEO",
    email: "bob.johnson@example.com",
    phone: "9876543210",
    website: "www.example.com",
    company: "XYZ Inc.",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 23,
    source: {
      leadSourceId: 3,
      leadSourceName: "Customer Event",
    },
    industry: "Apparel",
    status: "New",
    rating: "--None--",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Charlie",
    lastName: "Brown",
    middleName: null,
    gender: 1,
    title: "Engineer",
    email: "charlie.brown@example.com",
    phone: "5555555555",
    website: "www.example.com",
    company: "123 Industries",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 24,
    source: {
      leadSourceId: 4,
      leadSourceName: "External Referral",
    },
    industry: "Banking",
    status: "Working",
    rating: "Warm",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "David",
    lastName: "Davis",
    middleName: null,
    gender: 0,
    title: "Consultant",
    email: "david.davis@example.com",
    phone: "3333333333",
    website: "www.example.com",
    company: "Davis Corp",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 25,
    source: {
      leadSourceId: 5,
      leadSourceName: "Employee Referral",
    },
    industry: "Biotechnology",
    status: "Nurturing",
    rating: "Warm",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Emma",
    lastName: "Lee",
    middleName: null,
    gender: 0,
    title: "Analyst",
    email: "emma.lee@example.com",
    phone: "2222222222",
    website: "www.example.com",
    company: "Lee Enterprises",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 26,
    source: {
      leadSourceId: 1,
      leadSourceName: "--None--",
    },
    industry: "Agriculture",
    status: "New",
    rating: "Hot",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Frank",
    lastName: "Wilson",
    middleName: null,
    gender: 1,
    title: "Manager",
    email: "frank.wilson@example.com",
    phone: "6666666666",
    website: "www.example.com",
    company: "Wilson Co.",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 27,
    source: {
      leadSourceId: 2,
      leadSourceName: "Advertisement",
    },
    industry: "Apparel",
    status: "Working",
    rating: "--None--",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Grace",
    lastName: "Smith",
    middleName: null,
    gender: 0,
    title: "CEO",
    email: "grace.smith@example.com",
    phone: "9999999999",
    website: "www.example.com",
    company: "Smith Corp",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 28,
    source: {
      leadSourceId: 3,
      leadSourceName: "Customer Event",
    },
    industry: "Banking",
    status: "Unqualified",
    rating: "Hot",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Henry",
    lastName: "Brown",
    middleName: null,
    gender: 1,
    title: "Consultant",
    email: "henry.brown@example.com",
    phone: "8888888888",
    website: "www.example.com",
    company: "Brown LLC",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 29,
    source: {
      leadSourceId: 4,
      leadSourceName: "External Referral",
    },
    industry: "Biotechnology",
    status: "Nurturing",
    rating: "Hot",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Isabella",
    lastName: "Johnson",
    middleName: null,
    gender: 0,
    title: "Analyst",
    email: "isabella.johnson@example.com",
    phone: "7777777777",
    website: "www.example.com",
    company: "Johnson & Co.",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  },
  {
    leadId: 30,
    source: {
      leadSourceId: 5,
      leadSourceName: "Employee Referral",
    },
    industry: "Banking",
    status: "Working",
    rating: "Warm",
    addressInfor: {
      addressInformationId: 1,
      street: "123 ABC Street",
      city: "Cityville",
      province: "Provinceville",
      postalCode: "12345",
      country: "Countryland",
    },
    solution: "--None--",
    firstName: "Jack",
    lastName: "Lee",
    middleName: null,
    gender: 1,
    title: "Manager",
    email: "jack.lee@example.com",
    phone: "1111111111",
    website: "www.example.com",
    company: "Lee Financial",
    no_employee: null,
    createdBy: 1,
    createDate: "2024-06-10T17:00:00.000+00:00",
    editDate: "2024-06-10T17:00:00.000+00:00",
    editBy: 1,
    isDelete: 0,
  }
];